/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-05-23 01:43:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/Dev/Works/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/paldo5/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/Dev/Works/spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/paldo5/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1745466310420L));
    _jspx_dependants.put("/WEB-INF/views/includes/header.jsp", Long.valueOf(1747872938000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <title>팔도마켓</title>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@700&display=swap\" rel=\"stylesheet\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/dist/css/main.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\n");
      out.write("  <style>\n");
      out.write("    #playButton {\n");
      out.write("        position: absolute;\n");
      out.write("        bottom: 10px;\n");
      out.write("        left: 50%;\n");
      out.write("        transform: translateX(-50%);\n");
      out.write("        padding: 10px 20px;\n");
      out.write("        font-size: 16px;\n");
      out.write("        background-color: #111;\n");
      out.write("        color: white;\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 8px;\n");
      out.write("        cursor: pointer;\n");
      out.write("        opacity: 0.85;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("   <nav class=\"nav-bar\">\n");
      out.write("        <div class=\"nav-logo\">\n");
      out.write("  <a href=\"/\" style=\"text-decoration: none; color: inherit;\">\n");
      out.write("  <img src=\"/resources/images/GhPT6z6bMAEuP11.jpg\" alt=\"팔도마켓\" class=\"logo-img\" /> 팔도마켓\n");
      out.write("</a>\n");
      out.write("      </div>\n");
      out.write("        <div class=\"nav-menu\">\n");
      out.write("            <a href=\"/\">홈</a>\n");
      out.write("            <a href=\"/board/list\">게시판</a>\n");
      out.write("            <a href=\"/board/register\">글쓰기</a>\n");
      out.write("            <a href=\"#\">마이페이지</a>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>팔도마켓 | 메인</title>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <!-- Noto Sans 폰트 -->\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/dist/css/main.css\">\n");
      out.write("    <style>\n");
      out.write("    .logo-img {\n");
      out.write("        height: 38px;\n");
      out.write("        vertical-align: middle;\n");
      out.write("        margin-right: 10px;\n");
      out.write("        border-radius: 7px;\n");
      out.write("        box-shadow: 0 2px 8px rgba(0,0,0,0.07);\n");
      out.write("    }\n");
      out.write("    #playButton {\n");
      out.write("        position: absolute;\n");
      out.write("        bottom: 10px;\n");
      out.write("        left: 50%;\n");
      out.write("        transform: translateX(-50%);\n");
      out.write("        padding: 10px 20px;\n");
      out.write("        font-size: 16px;\n");
      out.write("        background-color: #111;\n");
      out.write("        color: white;\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 8px;\n");
      out.write("        cursor: pointer;\n");
      out.write("        opacity: 0.85;\n");
      out.write("    }\n");
      out.write("    </style>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/dist/css/product.css\">\n");
      out.write("    <title>중고폰 게시글 등록</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"product-register-container\">\n");
      out.write("    <h2 class=\"form-title\">📱 중고폰 상품등록</h2>\n");
      out.write("	<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/post/upload\" \n");
      out.write("	      method=\"post\" \n");
      out.write("	      enctype=\"multipart/form-data\" \n");
      out.write("	      class=\"image-upload-form\">\n");
      out.write("	    \n");
      out.write("	    <!-- ✅ 대표 이미지 업로드 -->\n");
      out.write("	    <div class=\"form-group\" style=\"display: inline-block; width: 100%;\">\n");
      out.write("	        <label>대표 이미지 업로드 <span class=\"required\">*</span></label>\n");
      out.write("	        <input type=\"file\" name=\"mainImage\" accept=\"image/*\" required />\n");
      out.write("	        <button type=\"submit\" class=\"btn-blue\" style=\"float: right;\">이미지 업로드</button>\n");
      out.write("	    </div>\n");
      out.write("	</form>\n");
      out.write("        \n");
      out.write("    <!-- ✅ enctype 반드시 포함 -->\n");
      out.write("    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/register\" \n");
      out.write("          method=\"post\" \n");
      out.write("          enctype=\"multipart/form-data\" \n");
      out.write("          class=\"product-form\">\n");
      out.write("\n");
      out.write("        <!-- 제목 -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label>제목 <span class=\"required\">*</span></label>\n");
      out.write("            <input type=\"text\" name=\"title\" required placeholder=\"예: 아이폰 13 미드나잇\" />\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- 모델명 -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label>모델명 <span class=\"required\">*</span></label>\n");
      out.write("            <input type=\"text\" name=\"product\" required placeholder=\"예: 아이폰 13\" />\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- 가격 -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label>가격 <span class=\"required\">*</span></label>\n");
      out.write("            <input type=\"number\" name=\"price\" required placeholder=\"예: 650000\" />\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- 브랜드 -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label>브랜드</label>\n");
      out.write("            <input type=\"text\" name=\"brand\" placeholder=\"예: Samsung, Apple 등\" />\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- 상품 상태 (라디오 버튼) -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label>상품 상태 <span class=\"required\">*</span></label>\n");
      out.write("            <div class=\"option-group\">\n");
      out.write("                <input type=\"radio\" id=\"cond1\" name=\"condition\" value=\"상\" checked>\n");
      out.write("                <label for=\"cond1\" class=\"btn-radio\">상</label>\n");
      out.write("\n");
      out.write("                <input type=\"radio\" id=\"cond2\" name=\"condition\" value=\"중\">\n");
      out.write("                <label for=\"cond2\" class=\"btn-radio\">중</label>\n");
      out.write("\n");
      out.write("                <input type=\"radio\" id=\"cond3\" name=\"condition\" value=\"하\">\n");
      out.write("                <label for=\"cond3\" class=\"btn-radio\">하</label>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- 판매 상태 (라디오 버튼) -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label>판매 상태</label>\n");
      out.write("            <div class=\"option-group\">\n");
      out.write("                <input type=\"radio\" id=\"stat1\" name=\"status\" value=\"판매중\" checked>\n");
      out.write("                <label for=\"stat1\" class=\"btn-radio\">판매중</label>\n");
      out.write("\n");
      out.write("                <input type=\"radio\" id=\"stat2\" name=\"status\" value=\"판매완료\">\n");
      out.write("                <label for=\"stat2\" class=\"btn-radio\">판매완료</label>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- 닉네임 -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label>닉네임 <span class=\"required\">*</span></label>\n");
      out.write("            <input type=\"text\" name=\"nickname\" required placeholder=\"판매자 닉네임 입력\" />\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- 비밀번호 -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label>비밀번호 (수정/삭제용) <span class=\"required\">*</span></label>\n");
      out.write("            <input type=\"password\" name=\"password\" required placeholder=\"4~12자 비밀번호\" />\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- 설명 -->\n");
      out.write("        <div class=\"form-group\">\n");
      out.write("            <label>설명 <span class=\"required\">*</span></label>\n");
      out.write("            <textarea name=\"description\" rows=\"6\" minlength=\"20\" required placeholder=\"20자 이상 상세 설명을 작성해 주세요.\"></textarea>\n");
      out.write("        </div>\n");
      out.write("    </form>\n");
      out.write("        <!-- 등록 버튼 -->\n");
      out.write("        <div class=\"form-actions\">\n");
      out.write("            <button type=\"submit\" class=\"btn-blue\">등록하기</button>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
